### ISSUE TITLE
Octoprint passing USB webcam, missing config files

### ISSUE THREAD

**Issue by DustyArmstrong** [OctoPrint/octoprint-docker#186]
## Question/Problem Description

I'm trying to pass a PS3 eye through to my container, using the methods laid out in the docker-compose file. I haven't had any issues with that, I can manually take a photo using `ffmpeg -f v4l2 -video_size 1280x720 -i /dev/video0 -frames 1 out.jpg ` and get an image as expected. 

Is there some additional work required? A lot of the resources / forum posts mention "octopi.txt", which obviously isn't relevant here. My config.yaml doesn't have anything about the camera, and doesn't resemble the one on this repo. I have had a USB webcam running on this exact Pi using the same method (MotioneyeOS on Docker), so it's "known good".

### System Details

```
version: '2.4'
services:
        octoprint:
                image: octoprint/octoprint
                container_name: octoprint
                restart: always
                ports:
                        - 80:80
                devices:
                        - /dev/ttyUSB0:/dev/ttyUSB0
                        - /dev/video0:/dev/video0
                volumes:
                        - ./octostore:/octoprint
                environment:
                        - ENABLE_MJPG_STREAMER=true
                        - CAMERA_DEV=/dev/video0
volumes:
        octostore:
```

```
Docker 20.10.5, build 55c4c88
```

## Describe your hardware

Ubuntu server 20.04 on a Raspi 4.

**Comment by DustyArmstrong** [comment]
Adding the flag `-y` to the compose file allowed the functionality. 

```
version: '2.4'
services:
        octoprint:
                image: octoprint/octoprint
                container_name: octoprint
                restart: always
                ports:
                        - 80:80
                devices:
                        - /dev/ttyUSB0:/dev/ttyUSB0
                        - /dev/video0:/dev/video0
                volumes:
                        - ./octostore:/octoprint
                environment:
                        - ENABLE_MJPG_STREAMER=true
                        - CAMERA_DEV=/dev/video0
                        - MJPG_STREAMER_INPUT=-y
volumes:
        octostore:
~                     
```
