### ISSUE TITLE
[BUG] Octoprint docker runs out of space on 4th image

### ISSUE THREAD

**Issue by repvik** [OctoPrint/octoprint-docker#204]
**Describe the bug**
I'm running 4 docker images, all with cameras. Whatever order I start them in, the last container started fails with the following error:
```
MJPG Streamer Version.: 2.0
[...]
libv4l2: error turning on stream: No space left on device
Unable to start capture: No space left on device

```

There's 95GB free space on the filesystem. 

**Container Details**

2021-06-06T14:17:51.966Z

Relevant bit of docker-compose:
```
  octoprint1:
    container_name: Octo1
    image: octoprint/octoprint
    hostname: Octo1
    restart: unless-stopped
    ports:
      - 81:80
    volumes:
      - octoprint1:/octoprint
      - /srv/octoprint_felles:/octoprint/octoprint/uploads
    environment:
      - CAMERA_DEV=/dev/video0
      - ENABLE_MJPG_STREAMER=true
      - MJPG_STREAMER_INPUT=-n -r 1280x960 -f 30
    devices:
      - /dev/TA_MK3Stock:/dev/ttyACM0
      - /dev/TA_MK3Stock_Cam:/dev/video0

```
df -h from within the container:
```
overlay         109G  8.8G   95G   9% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/sda3       109G  8.8G   95G   9% /octoprint
shm              64M     0   64M   0% /dev/shm
tmpfs           7.8G     0  7.8G   0% /proc/asound
tmpfs           7.8G     0  7.8G   0% /proc/acpi
tmpfs           7.8G     0  7.8G   0% /proc/scsi
tmpfs           7.8G     0  7.8G   0% /sys/firmware
```

**To Reproduce**
Create 4 instances of the above docker service. 
When started, the last one will fail.

**Expected behavior**
Expected the last instance started to start.
