### ISSUE TITLE
Make vcgencmd and PiSupport bundled plugin work on RaspberryPi hosts

### ISSUE THREAD

**Issue by oerkel47** [OctoPrint/octoprint-docker#207]
**Is your feature request related to a problem? Please describe.**
When using Octoprint-docker on a RPi, the bundled Plugin [PiSupport](https://github.com/OctoPrint/OctoPrint-PiSupport) doesn't load because it doesn't detect a RasperryPi. This means there will be no warning about undervoltage, throttling etc.

**Describe the solution you'd like**
Add information to the docs how to get the plugin and detection to work or integrate a solution that makes this "workaround"  unnecessary.

**Possible Solution**
add to docker-compose.yml:

     volumes:
        - /usr/bin/vcgencmd:/usr/bin/vcgencmd        
        - /usr/lib/aarch64-linux-gnu/libvcos.so.0:/usr/lib/aarch64-linux-gnu/libvcos.so.0        
        - /usr/lib/aarch64-linux-gnu/libvchiq_arm.so.0:/usr/lib/aarch64-linux-gnu/libvchiq_arm.so.0             
     privileged: true

With the privileged setting active, octoprint is able to determine the host as a Pi and enable the plugin. Adding the 3 other mounts gives it access to vcgencm (which doesn't work without privileged as well).

The paths for the files are only valid for aarch64, unsure where exactly they are on the 32 bit version of rpi os (google results suggest /opt/vc/lib and /opt/vc/bin)

**Other options**
Maybe integrate vcgencmd into the image directly to avoid privilege setting or find a way without privileged mode.
Google results suggest that adding/installing raspberrypi packages can do the trick (example: "RUN apk add raspberrypi" in Dockerfile which adds rpi support to alpine images).

**Additional context**
The privilege mode might not be desirable. Cap_add SYS_ADMIN is not enough.

**Comment by piter-pit** [comment]
for raspberry pi 4 32-bit I had to set up following volumes:
`     - /usr/bin/vcgencmd:/usr/bin/vcgencmd`
`     - /opt/vc/lib/libvcos.so:/usr/lib/arm-linux-gnueabihf/libvcos.so.0`
`     - /opt/vc/lib/libvchiq_arm.so:/usr/lib/arm-linux-gnueabihf/libvchiq_arm.so.0`

**Comment by Caroga** [comment]
For those running DietPi on a RPI3B+ 64bit, this is a working setup:

```yaml
version: '3.8'
services:
  octoprint:
    image: octoprint/octoprint:1.8.1
    restart: unless-stopped
    privileged: true
    ports:
      - 80:80
    volumes:
     - octoprint:/octoprint
     - /usr/bin/vcgencmd:/usr/bin/vcgencmd
     - /usr/lib/arm-linux-gnueabihf/libvcos.so.0:/usr/lib/arm-linux-gnueabihf/libvcos.so.0
     - /usr/lib/arm-linux-gnueabihf/libvchiq_arm.so.0:/usr/lib/arm-linux-gnueabihf/libvchiq_arm.so.0
    logging:
     options:
      max-size: "10m"
volumes:
  octoprint:
```

This has a pre-existing octoprint volume which you create simply like `docker volume create octoprint` before upping the docker compose file.
Log settings are not mandatory ofcourse.

**Comment by danielXengines** [comment]
Thank you for sharing Caroga, your solution worked for me. vcgencmd now works and now warnings reported on this issue. I am running a Raspi 4B with bullseye.

> ```yaml
>     volumes:
>      - octoprint:/octoprint
>      - /usr/bin/vcgencmd:/usr/bin/vcgencmd
>      - /usr/lib/arm-linux-gnueabihf/libvcos.so.0:/usr/lib/arm-linux-gnueabihf/libvcos.so.0
>      - /usr/lib/arm-linux-gnueabihf/libvchiq_arm.so.0:/usr/lib/arm-linux-gnueabihf/libvchiq_arm.so.0
> ```

**Comment by mcamou** [comment]
I'm also running octoprint in Docker on Ubuntu 22.04.2 LTS. After bind mounting `vcgencmd` and the shared libs, I also get the following:

```
root@67d6642b12fc:/octoprint# vcgencmd
vcgencmd: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by vcgencmd)
vcgencmd: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/aarch64-linux-gnu/libvchiq_arm.so)
vcgencmd: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/aarch64-linux-gnu/libvcos.so)
root@67d6642b12fc:/octoprint# 
```

It looks like the issue is different versions of libc used by Raspbian/Debian vs. Ubuntu. Looking at all the libraries that `vcgencmd` references (on the host system):

```
$ ldd /usr/bin/vcgencmd 
        linux-vdso.so.1 (0x0000ffffb32d7000)
        libvchiq_arm.so => /lib/aarch64-linux-gnu/libvchiq_arm.so (0x0000ffffb3260000)
        libvcos.so => /lib/aarch64-linux-gnu/libvcos.so (0x0000ffffb3240000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffffb3090000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffffb329e000)
```

`linux-vdso.so.1` is a virtual shared library provided by the kernel. I tried some tricks with bind-mounting the other 4 shared libs into `/opt/vcgencmd/lib` and setting `LD_LIBRARY_PATH` to load them. I got as far as `vcgencmd` starting but dumping core:

```
# LD_LIBRARY_PATH=/opt/vcgencmd/lib /opt/vcgencmd/bin/vcgencmd
Segmentation fault (core dumped)
# LD_LIBRARY_PATH=/opt/vcgencmd/lib /opt/vcgencmd/bin/vcgencmd get_throttled
Illegal instruction (core dumped)
```

At this point the only "viable" option I see is reflashing using Raspbian instead of Ubuntu. Not THAT much of a problem since I'm mounting `/home/ubuntu/` via NFS from my NAS, and I changed the `volume` declaration in `docker-compose.yml` to bind-mount `/home/ubuntu/octoprint` (so that all my configurations are safe on my NAS in case e.g. of an SD failure), but still... not good.

**Comment by mcamou** [comment]
Here's the process to get `vcgencmd` and the shared libs from another image: https://raspberrypi.stackexchange.com/a/120976. Perhaps the `Dockerfile` could be modified to add these?

**Comment by mcamou** [comment]
I ended up flashing Raspbian Buster. I wanted the version to be the same as the one in the Docker image to prevent .so version issues. My main gripe is that it's 32-bit only (which, now that I think about it, might have been the issue with Ubuntu)

This is my `docker-compose.yml`:

```
version: '2.4'

services:
  octoprint:
    image: octoprint/octoprint:latest
    restart: unless-stopped
    privileged: true
    ports:
      - 80:80
    volumes:
      - /home/ubuntu/octoprint:/octoprint
      - /usr/bin/vcgencmd:/usr/bin/vcgencmd
      - /opt/vc/lib/libvchiq_arm.so:/lib/arm-linux-gnueabihf/libvchiq_arm.so
      - /opt/vc/lib/libvcos.so:/lib/arm-linux-gnueabihf/libvcos.so
```

Everything else is commented out. I set `privileged: true` so that the container will start even if the printer is turned off, I assume that it's also necessary for `vcgencmd` to work.

With this, `vcgencmd get_throttled` works inside the container, and I now see the RPi temperature in the navbar (courtesy of the "Navbar Temperature Plugin").
