### ISSUE TITLE
[BUG] docker-compose configuration incompatible with Discovery Plugin

### ISSUE THREAD

**Issue by JeWe37** [OctoPrint/octoprint-docker#210]
**Describe the bug**
With the current docker-compose file bonjour/avahi/zeroconf auto-discovery does not work.

**Container Details**

Don't think this matters here:
2021-11-02T17:31:14.962Z

**To Reproduce**
1. Create a container with the docker-compose file
2. Observe that say Cura's Octoprint plugin or Windows Explorer's network tab won't show Octoprint.

**Expected behavior**
They should show up I guess?

**Additional context**
I have solved it: For similar SSDP problems you usually see using host networking(`network_mode: host`) suggested. On my RaspberryPi that did not work though, I instead had to set up a macvlan network, which for some reason then did work just fine. Further investigation may be required, which is why this isn't a pull request.

```
version: '2.4'

services:
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    # required for using discovery
    networks:
      octoprint_vlan:
        ipv4_address: 192.168.0.242
    # ports:
    #   - 80:80
    devices:
    # use `python -m serial.tools.miniterm` to see what the name is of the printer
    #  - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyUSB0:/dev/ttyUSB0
    #  - /dev/video0:/dev/video0
    volumes:
     - octoprint:/octoprint
    # uncomment the lines below to ensure camera streaming is enabled when
    # you add a video device
    #environment:
    #  - ENABLE_MJPG_STREAMER=true

  ####
  # uncomment if you wish to edit the configuration files of octoprint
  # refer to docs on configuration editing for more information
  ####

  #config-editor:
  #  image: linuxserver/code-server
  #  ports:
  #    - 8443:8443
  #  depends_on:
  #    - octoprint
  #  restart: unless-stopped
  #  environment:
  #    - PUID=0
  #    - GUID=0
  #    - TZ=America/Chicago
  #  volumes:
  #    - octoprint:/octoprint

volumes:
  octoprint:

networks:
  octoprint_vlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
          ip_range: 192.168.0.240/28
```
