### ISSUE TITLE
octoprint wont start: 

### ISSUE THREAD

**Issue by jonwilliams84** [OctoPrint/octoprint-docker#214]
I am trying to run this image in a kubernetes cluster using virtualhere client on the node that I am pinning the pod to in order to mount the USB device (printer) connected remotely to another pi-zero.

I have tested this and it worked perfectly for the first time the pod runs. 

Here is my deployment.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: octoprint
  name: octoprint
  namespace: octoprint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octoprint
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: octoprint
    spec:
      nodeName: tcl-k8s-1
      containers:
      - image: octoprint/octoprint
        name: octoprint
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /octoprint
            name: datastore
          - mountPath: /dev/ttyACM0
            name: ttyacm
      volumes:
       - name: ttyacm
         hostPath:
           path: /dev/ttyACM0
       - name: datastore
         persistentVolumeClaim:
           claimName: pvc-octoprint
```
The pvc (using longhorn):
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-octoprint
  namespace: octoprint
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
```

As mentioned the first time this spun up it worked flawlessly. The node where the pod is scheduled has the printer connected via VirtualHere:
```
VirtualHere Client IPC, below are the available devices:
(Value in brackets = address, * = Auto-Use)

Raspberry Hub (octopi:7575)
  *--> Maple (octopi.115) (In-use by you)
```
lsusb:
```
Bus 009 Device 008: ID 1eaf:0029 LeafLabs Maple
```
...and Octoprint worked and picked up the /dev/ttyACM device and I was able to do a test print without any issue, as if the host was directly connected to the printer.

Fast forward a couple of days, now when the pod comes up, I try and hit the octoprint service that I have exposed and added ingress for which was working perfectly, gets a 503 error page. 

The logs of the pod are just being spammed with:
```
Error: Invalid value for '--port': tcp://10.43.71.129:80 is not a valid integer
Usage: octoprint [OPTIONS] COMMAND [ARGS]...
Try 'octoprint --help' for help.
```

So, at first I think, maybe the PVC/data held in the volume is corrupt somehow. I delete the deployment, and the pvc and then recreate it. Same error. No matter what I try, the octoprint service within the container never comes up.

I have checked the s6 service supervisor / controller and the command its using to launch octoprint looks fine:
```
root@octoprint-66fbd6d67b-mgft2:/# cat /var/run/s6/services/octoprint/run
#!/usr/bin/with-contenv sh

exec octoprint serve --iknowwhatimdoing --host 0.0.0.0 --port 5000 --basedir /octoprint/octoprint
```

Any thoughts?  I know this is probably not the usual deployment method!
