### ISSUE TITLE
[BUG] Running armv7 container on aarch64 raspberry os host breaks with Loading failed - Passive login failed

### ISSUE THREAD

**Issue by Apfelwurm** [OctoPrint/octoprint-docker#223]
**Describe the bug**
If you start a latest octoprint container with platform linux/arm/v7 specified on an aarch64 raspbian (raspberry pi 4) and open a web Browser it returns 

``` 
Loading failed
Passive login failed. Please check your [browser's error console](https://faq.octoprint.org/browser-console) and [octoprint.log](https://faq.octoprint.org/logs) for possible reasons.Also make sure that the server is actually running by reloading this page.
```

if i change from arm/v7 to aarch64 everything works like it is intended, but since i would like to use the 32bit version i noticed the problem

**Container Details**

2022-01-20T11:23:25.806Z

**To Reproduce**
- use the following docker-compose.yml
```
version: '2.4'

services:
  octoprint:
    image: octoprint/octoprint
    platform: linux/arm/v7
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
     - /var/octoprint:/octoprint
```

**Expected behavior**
The container should work normally and bring up the initial setup wizzard

**Screenshots**
![https://user-images.githubusercontent.com/20586182/104126966-c0686e00-535f-11eb-9ac1-5b097c703520.png](https://user-images.githubusercontent.com/20586182/104126966-c0686e00-535f-11eb-9ac1-5b097c703520.png)

**Server:**
- Raspberry Pi 4 - 4gb
- Raspberry OS ( Debian GNU/Linux 11 (bullseye) )
- Docker Version: 20.10.14
- Docker Compose version v2.4.1

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Browser: Brave Version 1.36.111 Chromium: 99.0.4844.51
