### ISSUE TITLE
Can't get webcam working

### ISSUE THREAD

**Issue by jflkjjlkdsajlkdsajlkjlkjdsaljdsa** [OctoPrint/octoprint-docker#248]
## Question/Problem Description

I'm struggling to get the webcam working when using docker and octoprint (the same webcam works flawlessly with octopi). One webcam is located under /dev/video0 and the other one under /dev/video2. It should work according to the docs but I don't get any video. he instances of octoprint are working and are able to connect to the machines. Just no webcam image from any of the cameras.

### System Details

I'm using stock raspbian lite 64bit and portainer on a rpi 4.  Is there maybe some dependency missing?

```
version: '2.4'
services:
  flashforge:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 5000:5000
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/video0:/dev/video0
    volumes:
      - /root/octoprint/flashforge:/octoprint
    # uncomment the lines below to ensure camera streaming is enabled when
    # you add a video device
    environment:
      - ENABLE_MJPG_STREAMER=true
      - CAMERA_DEV=/dev/video0
  sculpfun:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 5001:5000
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/video2:/dev/video2
    volumes:
      - /root/octoprint/sculpfun:/octoprint
    # uncomment the lines below to ensure camera streaming is enabled when
    # you add a video device
    environment:
      - ENABLE_MJPG_STREAMER=true
      - CAMERA_DEV=/dev/video2
```

Include the output of `docker version` (and `docker-compose` version if using compose):

```
version output here
```

## Describe your hardware

Example (replace with your information):   running on raspberry pi 4 64bit raspbian lite
