### ISSUE TITLE
[BUG] Webassets are not loaded when X-Script-Name is set

### ISSUE THREAD

**Issue by wolkenschieber** [OctoPrint/octoprint-docker#251]
**Describe the bug**

Webassets are not loaed, when a custom path through `X-Script-Name` is set.

**Container Details**

My compose file looks like:
```yaml
version: '3.9'

services:
  octoprint:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.octoprint.entrypoints=web"
      - "traefik.http.routers.octoprint.rule=PathPrefix(`/octoprint`)"
      - "traefik.http.services.octoprint.loadbalancer.server.port=80"
      - "traefik.http.middlewares.opPathHeader.headers.customrequestheaders.X-Script-Name=/octoprint"
      - "traefik.http.routers.octoprint.middlewares=opPathHeader@docker"
    image: octoprint/octoprint
    restart: unless-stopped
    volumes:
     - ./config:/octoprint
    networks:
     - proxy

networks:
  proxy:
    external: true
```

**To Reproduce**

Navigate to http://SERVER/octoprint/. The page won't load. File from `static/webassets` report 404.

**Screenshots**

![image](https://user-images.githubusercontent.com/5024238/224517295-fc3f34b6-737b-4035-b9cd-f98ebd6b5bf1.png)
