### ISSUE TITLE
Feature: Get last `n` releases || releases compatible with semver range

### ISSUE THREAD

**Issue by LongLiveCHIEF** [OctoPrint/octoprint-docker#82]
Often if you're doing something like building a docker image around a product (for me it's the official octoprint/octoprint image), then you need to not only build an image for the latest release of a product, but several of the previous releases.

It would be great to be able to specify the last n releases, or to specify a semver input and get all tags that match.

Here's what I'm thinking this could look like: (see example of creating a matrix in one job and passing it to another from [github actions docs](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#example-6)

```yaml
jobs:
  releases:
    outputs:
      matrix: ${{ steps.releases.outputs.matrix }}
    steps:
      # produces a matrix with a key of `matrix`
      - name: Get Releases
         id: releases
         uses: pozetroninc/github-action-get-latest-release
         with: 
            tags_repo: some/repository
            tag_expansion_rule: '^1.0.0'
  build:
    needs: releases
    strategy: 
      matrix: ${{ fromJson(needs.releases.outputs.matrix) }}
```
