### ISSUE TITLE
Unexpected error while connecting to serial port /dev/ttyACM0

### ISSUE THREAD

**Issue by qaqak** [OctoPrint/octoprint-docker#89]
## Question/Problem Description

I keep getting this error when I click "Connect"
What do I have to do?

### System Details

I'm running OctoPrint docker using the following `docker-compose.yml` file:

```
version: '2.2'

services:
  ender3:
    restart: unless-stopped
    image: octoprint/octoprint
    ports:
      - 4000:5000
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
    volumes:
     - /root/OctoPrint/Ender3:/home/OctoPrint

  mjpg-streamer:
    restart: unless-stopped
    image: openhorizon/mjpg-streamer-pi3
    # This image just takes the raw mjpg-streamer args -- set to 720p,30 fps
    command: ./mjpg_streamer -o "output_http.so -w ./www" -i "input_uvc.so -r 1280x720 -d /dev/video0 -f 30"
    devices:
      - /dev/video0:/dev/video0
    ports:
      - 8080:8080

```

## Describe your hardware

Running on Raspberry Pi 4 64bit Ubuntu Server 20.04
